---
name: Retrieve Device Settings
short_description: Retrieve the current settings on the device
example_usage:
  java:
    |
      Map<String, Object> settings = driver.getSettings();
  javascript_wd:
    |
      await driver.settings();
  javascript_wdio:
    |
      let settings = driver.getSettings();
  ruby:
    |
      get_settings
  ruby_core:
    |
      @driver.get_settings
  python:
    |
      self.driver.get_settings

client_docs:
  java: "https://appium.github.io/java-client/io/appium/java_client/HasSettings.html#getSettings--"
  javascript_wdio: "http://webdriver.io/api/mobile/settings.html"
  javascript_wd: "https://github.com/admc/wd/blob/master/lib/commands.js#L3018"
  ruby: "https://www.rubydoc.info/github/appium/ruby_lib_core/Appium/Core/Device#get_settings-instance_method"
  ruby_core: "https://www.rubydoc.info/github/appium/ruby_lib_core/Appium/Core/Device#get_settings-instance_method"
  python: "https://github.com/appium/python-client/blob/af1988e55e9856cff3a918e901f92d065195b904/appium/webdriver/webdriver.py#L1131"

# Driver support by platform
driver_support:
  ios:
    xcuitest: true
    uiautomation: true
  android:
    espresso: true
    uiautomator2: true
    uiautomator: true
  mac:
    mac: true
  windows:
    windows: true
client_support:
  java: true
  python: false
  ruby: false
  php: false
  csharp: false
  javascript_wd: true
  javascript_wdio: true


# Information about the HTTP endpoints
endpoint:
  url: /session/:session_id/appium/settings
  method: GET
  url_parameters:
    - name: session_id
      description: ID of the session to route the command to
  response:
    - type: array<object>
      description: a JSON hash of all the currently specified settings, see [Settings API](/docs/en/advanced-concepts/settings.md).


# Links to specifications. Should link to at least one specification
specifications:
  jsonwp: https://github.com/appium/appium-base-driver/blob/master/lib/protocol/routes.js#L454
