name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Node Setup
        uses: actions/setup-node@v2.4.1

        # this is required for Appium's internal 'npm link' to work, given that 'npm link' always
        # uses the global node modules folder as an intermediary
      - name: Node Perms Fix
        run: sudo chown -R "$USER:" /usr/local/lib/node_modules

      - name: Code Checkout
        uses: actions/checkout@v2

      - name: Install
        run: npm install

      - name: Package Bootstrap
        run: npm run bootstrap

      - name: Transpile
        run: npm run build

      - name: Lint
        run: npm run test:lint

        # don't waste 20 minutes installing opencv if we don't get past lint
      - name: E2E Install
        run: npm install opencv4nodejs

      - name: Unit Tests
        run: npm run test:unit

      - name: E2E Tests
        run: npm run test:e2e
