INHERIT: ../../docutils/base-mkdocs.yml
site_name: Appium Documentation
repo_url: https://github.com/appium/appium
repo_name: appium/appium
edit_uri: edit/master/packages/appium/docs
copyright: Copyright &copy; 2012 OpenJS Foundation - <a href="#__consent">Change cookie settings</a>

theme:
  logo: assets/images/appium-logo-white.png
  favicon: assets/images/appium-logo.png

plugins:
  redirects:
    redirect_maps:
      'ecosystem/build-drivers.md': 'developing/build-drivers.md'
      'ecosystem/build-plugins.md': 'developing/build-plugins.md'
      'ecosystem/build-docs.md': 'developing/build-docs.md'
      'reference/commands/base-driver.md': 'commands/base-driver.md'
      'reference/commands/execute-driver-plugin.md': 'commands/execute-driver-plugin.md'
      'reference/commands/fake-driver.md': 'commands/fake-driver.md'
      'reference/commands/images-plugin.md': 'commands/images-plugin.md'
      'reference/commands/relaxed-caps-plugin.md': 'commands/relaxed-caps-plugin.md'
      'reference/commands/universal-xml-plugin.md': 'commands/universal-xml-plugin.md'

extra_css:
  - assets/stylesheets/extra.css

extra:
  homepage: /
  version:
    provider: mike
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/AppiumDevs
  alternate:
    - name: English
      link: /docs/en/ 
      lang: en
    - name: 日本
      link: /docs/ja/
      lang: ja
    - name: 中文简体
      link: /docs/zh/
      lang: zh
