INHERIT: ../../docutils/base-mkdocs.yml
site_name: Appium Documentation
repo_url: https://github.com/appium/appium
repo_name: appium/appium
edit_uri: edit/master/packages/appium/docs
copyright: |
  <p>Copyright <a href="https://openjsf.org">OpenJS Foundation</a> and Appium contributors. All rights reserved. The <a href="https://openjsf.org">OpenJS Foundation</a> has registered trademarks and uses trademarks.  For a list of trademarks of the <a href="https://openjsf.org">OpenJS Foundation</a>, please see our <a href="https://trademark-policy.openjsf.org">Trademark Policy</a> and <a href="https://trademark-list.openjsf.org">Trademark List</a>. Trademarks and logos not indicated on the <a href="https://trademark-list.openjsf.org">list of OpenJS Foundation trademarks</a> are trademarks&trade; or registered&reg; trademarks of their respective holders. Use of them does not imply any affiliation with or endorsement by them.</p>
  <p><a href="https://openjsf.org">The OpenJS Foundation</a> | <a href="https://terms-of-use.openjsf.org">Terms of Use</a> | <a href="https://privacy-policy.openjsf.org">Privacy Policy</a> | <a href="https://bylaws.openjsf.org">Bylaws</a> | <a href="https://code-of-conduct.openjsf.org">Code of Conduct</a> | <a href="https://trademark-policy.openjsf.org">Trademark Policy</a> | <a href="https://trademark-list.openjsf.org">Trademark List</a> | <a href="https://www.linuxfoundation.org/cookies">Cookie Policy</a></p><a href="#__consent">Change cookie settings</a>

theme:
  logo: assets/images/appium-logo-white.png
  favicon: assets/images/appium-logo.png
  custom_dir: overrides

plugins:
  blog:
    enabled: true
    post_excerpt: required
  redirects:
    redirect_maps:
      'intro/requirements.md': 'quickstart/requirements.md'
      'ecosystem/build-drivers.md': 'developing/build-drivers.md'
      'ecosystem/build-plugins.md': 'developing/build-plugins.md'
      'ecosystem/build-docs.md': 'developing/build-docs.md'
      'reference/commands/base-driver.md': 'reference/api/index.md'
      'reference/commands/execute-driver-plugin.md': 'reference/api/plugins.md#execute-driver-plugin'
      'reference/commands/images-plugin.md': 'reference/api/plugins.md#images-plugin'
      'reference/commands/relaxed-caps-plugin.md': 'reference/api/plugins.md#relaxed-caps-plugin'
      'reference/commands/universal-xml-plugin.md': 'reference/api/plugins.md#universal-xml-plugin'
      'commands/index.md': 'reference/api/index.md'
      'commands/base-driver.md': 'reference/api/index.md'
      'commands/execute-driver-plugin.md': 'reference/api/plugins.md#execute-driver-plugin'
      'commands/images-plugin.md': 'reference/api/plugins.md#images-plugin'
      'commands/relaxed-caps-plugin.md': 'reference/api/plugins.md#relaxed-caps-plugin'
      'commands/storage-plugin.md': 'reference/api/plugins.md#storage-plugin'
      'commands/universal-xml-plugin.md': 'reference/api/plugins.md#universal-xml-plugin'
      'cli/index.md': 'reference/cli/index.md'
      'cli/args.md': 'reference/cli/server.md'
      'cli/env-vars.md': 'reference/cli/env-vars.md'
      'cli/extensions.md': 'reference/cli/extensions.md'
      'cli/setup.md': 'reference/cli/setup.md'
      'contributing/config-system.md': 'developing/config-system.md'
      'contributing/develop.md': 'contributing/index.md'

extra_css:
  - assets/stylesheets/extra.css

extra:
  homepage: /
  version:
    provider: mike
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/AppiumDevs
  alternate:
    - name: English
      link: /docs/en/
      lang: en
    - name: 日本
      link: /docs/ja/
      lang: ja
    - name: 中文简体
      link: /docs/zh/
      lang: zh
