INHERIT: ../../docutils/base-mkdocs.yml
site_name: Appium Documentation
repo_url: https://github.com/appium/appium
repo_name: appium/appium
copyright: Copyright &copy; 2012 - 2022 OpenJS Foundation

theme:
  logo: assets/images/appium-logo-white.png
  favicon: assets/images/appium-logo.png
  features:
    - navigation.sections

extra_css:
  - assets/stylesheets/extra.css

extra:
  homepage: /
  version:
    provider: mike
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/AppiumDevs
  alternate:
    - name: English
      link: /docs/en/ 
      lang: en
    - name: 日本
      link: /docs/ja/
      lang: ja
    - name: 中文简体
      link: /docs/zh/
      lang: zh
