name: License Checks
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'
permissions:
  contents: read

jobs:
  fossa-check:
    name: Run FOSSA Analysis
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@24cb9080177205b6e8c946b17badbe402adc938f # v3
        with:
          ref: master
      - name: Install dependencies
        uses: bahmutov/npm-install@cb39a46f27f14697fec763d60fb23ad347e2befa # tag=v1
      - name: Install fossa-cli
        run: ./scripts/install-fossa.sh -d
      - name: Run FOSSA analysis
        run: |
          fossa analyze
          fossa test
    env:
      FOSSA_API_KEY: ${{secrets.FOSSA_API_KEY}}
