name: License Checks
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'
permissions:
  contents: read

jobs:
  fossa-check:
    name: Run FOSSA Analysis
    runs-on: ubuntu-latest
    env:
      FOSSA_API_KEY: ${{secrets.FOSSA_API_KEY}}
    if: github.repository == 'appium/appium'
    steps:
      - uses: actions/checkout@v4
        with:
          ref: master
      - name: Install dependencies
        uses: bahmutov/npm-install@v1
      - name: Install fossa-cli
        run: curl -H 'Cache-Control: no-cache' https://raw.githubusercontent.com/fossas/fossa-cli/master/install-latest.sh | bash
      - name: Run FOSSA analysis
        run: |
          fossa analyze
          fossa test
