name: License Checks
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'
permissions:
  contents: read

jobs:
  fossa-check:
    name: Run FOSSA Analysis
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # tag=v3
        with:
          ref: '2.0'
      - name: fossa analyze
        run: |
          npm install
          curl -sS -H 'Cache-Control: no-cache' https://raw.githubusercontent.com/fossas/fossa-cli/master/install-latest.sh | bash
          fossa analyze
          fossa test
    env:
      FOSSA_API_KEY: ${{secrets.FOSSA_API_KEY}}
